version: '2'

services:

    db:
        image: mysql
        restart: always        
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: secret           
        ports:
              - 3306:3306    

    adminer:
        image: adminer
        restart: always
        ports:
            - 8085:8080
